# Generated by Django 5.2.11 on 2026-02-10 11:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0002_case_priority'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='priority',
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_analyst',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='analyst_cases', to=settings.AUTH_USER_MODEL),
        ),
    ]
