# Generated by Django 5.2.11 on 2026-02-10 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0004_analystreport_delete_caseanalysis'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaseAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_summary', models.TextField()),
                ('insights', models.TextField()),
                ('patterns_identified', models.TextField(blank=True)),
                ('recommended_status', models.CharField(choices=[('open', 'Keep Open'), ('in_review', 'Move to Review'), ('closed', 'Recommend Closure')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('analyst', models.ForeignKey(limit_choices_to={'role': 'analyst'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cases.case')),
            ],
        ),
        migrations.DeleteModel(
            name='AnalystReport',
        ),
    ]
