# Generated by Django 5.2.11 on 2026-02-10 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_caseanalysis_delete_analystreport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='caseanalysis',
            name='recommended_status',
            field=models.CharField(choices=[('open', 'Keep Open'), ('investigating', 'Move to Review'), ('closed', 'Recommend Closure')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Evidence',
        ),
    ]
