# Generated by Django 5.2.11 on 2026-02-10 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_caseanalysis_recommended_status_and_more'),
        ('evidence', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='evidence',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_evidences', to='cases.case'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='file',
            field=models.FileField(upload_to='case_evidence/'),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='hash_code',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='evidence',
            name='uploaded_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='case_uploaded_evidences', to=settings.AUTH_USER_MODEL),
        ),
    ]
